// <auto-generated />
namespace OAuthServer.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Configuracoes_Iniciais : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Configuracoes_Iniciais));
        
        string IMigrationMetadata.Id
        {
            get { return "201711281843445_Configuracoes_Iniciais"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
